Remove addVsocksHandler from loadSnapshotHandlerList
vhive-serverless/firecracker-go-sdk pull request #1
Opened 2023-09-08 07:46 UTC by CuriousGeorgiy

*Description of changes:*

* According to the firecracker OpenAPI specification [1], creating vsock
devices is only a pre-boot request, so adding vsocks after loading a
snapshot fails. It also seems redundant, since the VM loaded from a
snapshot restores vsocks anyways.

* Forward the `container_snapshot_path` parameter of the firecracker load
snapshot request.

1. https://github.com/firecracker-microvm/firecracker/blob/56aeeac51c00b449a45be4542b3e807d34690ba7/src/api_server/swagger/firecracker.yaml#L676-L678

2023-09-08 11:10 UTC, ustiugov requested changes
minor comment

2023-09-08 11:10 UTC, ustiugov commented on handlers.go
> -	AddVsocksHandler,
comment out and leave an explanation

2023-09-08 11:31 UTC, CuriousGeorgiy commented on handlers.go
> -	AddVsocksHandler,
Done.

2023-09-10 09:35 UTC, ustiugov approved these changes

2023-09-10 09:35 UTC, merged